routes/web.php

<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('', function () {
    $products = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(12)->get();
    $products_new = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(6)->get();
    return view('home', compact('products', 'products_new'));
    return view('home');
});





//Route::post('single/comment_product2', function () {
//    return array();
//});

Route::post('/login', 'LoginController@showLogin');
Route::post('/login', 'LoginController@processLogin');
Route::get('logout', function() {
    Auth::logout(); // logout user
    return Redirect::to('/login');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/products', 'HomeController@index1')->name('products');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/vieworders', 'HomeController@vieworders')->name('vieworders');
Route::resource('/vieworders', 'ViewOrderController');

Route::get('/products', 'HomeController@index1')->name('products');
Route::get('/single/{id}', 'HomeController@index2')->name('product_details');
Route::get('/category_products/{id}', 'HomeController@get_products_by_category')->name('product_category');
Route::get('/cart', 'HomeController@index3')->name('cart');
Route::get('/admin', 'HomeController@index4')->name('admin');
Route::get('admin/comments/{id}/reply', 'AdminCommentsController@getReplyComment');
Route::get('admin/categories/{id}/child_categories', 'AdminCategoriesController@getChildCategory');
Route::post('single/comment_product2', 'HomeController@comment_product')->name('comment_product2');
Route::post('single/reply_product', 'HomeController@reply_product')->name('reply_product');
Route::post('/edit/{id}','HomeController@del_img')->name('del_img');
Route::resource('/profile','ClientController');
Route::resource('admin/products', 'AdminProductController', array('as' => 'admin'));
Route::resource('admin/categories', 'AdminCategoriesController', array('as' => 'admin'));
Route::resource('admin/users', 'AdminUserController', array('as' => 'admin'));
Route::resource('admin/comments', 'AdminCommentsController', array('as' => 'admin'));
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('comment', function(Request $request) {
    $comment = App\Comment::create($request->input());
    return response()->json($comment);
});

Route::get('/getsize', 'HomeController@getSizeProduct');
Route::get('/addtocart', 'HomeController@getSizeAddtoCart');
Route::get('/addtocart/{id}', 'HomeController@getAddToCart');
Route::get('product/delete/{id}', 'HomeController@removeItem');
Route::get('product/deductbyone/{id}', 'HomeController@deductByOne');
Route::get('/shoppingcart', 'HomeController@getCart');
Route::get('/shipping', 'HomeController@Shipping');
Route::get('search','HomeController@getSearch')->name('search'); //search by name product

Route::get('/search-price','HomeController@searchprice')->name('searchprice'); //search by price, size...
//Route::post('/searchprice', 'HomeController@searchprice');

Route::group(['middleware' => ['adminLogin']], function () {
    Route::resource('admin/users','AdminUserController', array('as' =>'admin'));
    Route::resource('admin/categories','AdminCategoriesController', array('as' =>'admin'));
    Route::resource('admin/products','AdminProductController', array('as' =>'admin'));
    Route::resource('admin/comments','AdminCommentsController', array('as' =>'admin'));    
});
Route::resource('admin/orders','OrderController', array('as' => 'admin'));

resources/views/about.blade.php
@extends('layouts.index')
@section('container')

<div class="agile-about-top">
    <!--    <div class="container">-->
    <h2 class="tittle-w3">Giới <span>thiệu</span></h2>
    <div class="about-section">
        <div class="col-md-7 ab-left">
            <div class="grid">
                <div class="h-f">
                    <figure class="effect-jazz">
                        <img src="images/s1.jpg" alt="img25">
                        <figcaption>
                            <h4>Chất lượng <span>hàng đầu</span></h4>
                            <p>Bảo đảm an toàn vệ sinh thực phẩm, thực phẩm luôn tươi mới.</p>
                        </figcaption>			
                    </figure>

                </div>
                <div class="h-f">
                    <figure class="effect-jazz">
                        <img src="images/s2.jpg" alt="img25">
                        <figcaption>
                            <h4>Thức ăn <span>ngon</span></h4>
                            <p>Với những món ăn đầy đủ dinh dưỡng</p>
                        </figcaption>			
                    </figure>

                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="col-md-5 ab-text">
            <h3 class="tittle-w3"><span>Sứ mệnh </span>của chúng tôi.</h3>
            <p>5 Pandas là website chính thức của chuỗi cửa hàng thức ăn 5PANDAS nổi tiếng. Ngoài việc cung 
                cấp các món ăn ngon của cửa hàng đến thực khách. Chúng tôi còn liên kết với các chuỗi nhà hàng nổi
                tiếng khác để đem đến cho các bạn thật nhiều món ăn ngon miệng. Chất lượng hàng đầu, giá thành hợp 
                lý và được đưa đến tận nhà một cách nhanh chóng, đảm bảo vệ sinh an toàn thực phẩm.
                <span>Bên cạnh đó chúng tôi còn chú ý đến việc xây dựng những khẩu phần ăn đầy đủ dinh dưỡng giúp cơ thể luôn có một năng lượng tràn đầy.</span></p>
        </div>
        <div class="clearfix"> </div>
    </div>
    <!--    </div>-->
</div>
<div class="count-agileits">
    <div id="particles-js"></div>

    <div class="count-grids">
        <h3 class="tittle-w3">Số liệu <span>thống kê</span></h3>
        <div class="count-bgcolor-w3ls">
            <div class="col-md-4 count-grid">
                <i class="fa fa-cutlery" aria-hidden="true"></i>
                <div class="count hvr-bounce-to-bottom">
                    <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='1052' data-delay='.5' data-increment="100">
                    </div>
                    <span></span>
                    <h5>Số lượng sản phẩm</h5>
                </div>
            </div>
            <div class="col-md-4 count-grid">
                <i class="fa fa-users" aria-hidden="true"></i>
                <div class="count hvr-bounce-to-bottom">
                    <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='372' data-delay='.5' data-increment="100">372</div>
                    <span></span>
                    <h5>Số lượng khách truy cập</h5>
                </div>
            </div>
            <div class="col-md-4 count-grid">
                <i class="fa fa-user-plus" aria-hidden="true"></i>
                <div class="count hvr-bounce-to-bottom">
                    <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='105209' data-delay='.5' data-increment="100">105209</div>
                    <span></span>
                    <h5>Số lượng thành viên</h5>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<div class="team">
    <div class="container">
        <h3 class="tittle-w3"><span>Đầu bếp </span>của chúng tôi</h3>
        <div class="team-row">
            <div class="col-md-3 team-grids wow fadeInUp animated" data-wow-delay=".5s">
                <h5>Duyen <span>Ngo</span></h5>
                <p>Chúng tôi tự hào khi là một thành viên và được làm việc cùng 5 Pandas</p>
                <div class="social-bnr-agileits about-agile">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>					
                    </ul>
                </div>
                <div class="team-img">
                    <img src="images/duyen.jpg" alt="">
                </div>
            </div>
            <div class="col-md-3 team-grids team-mdl wow fadeInUp animated" data-wow-delay=".5s">
                <h5>Anh <span>Nguyen</span></h5>
                <p>Tại 5 Pandas tôi đã học được rất nhiều điều với sự hỗ trợ tận tình của mọi người.</p>
                <div class="social-bnr-agileits about-agile">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>					
                    </ul>
                </div>
                <div class="team-img">
                    <img src="images/anhn.jpg" alt="">
                </div>
            </div>
            <div class="col-md-3 team-grids team-mdl1 wow fadeInUp animated" data-wow-delay=".5s">
                <h5>Thuong <span>Nguyen</span></h5>
                <p>Môi trường làm việc luôn đặt chất lượng của mỗi sản phẩm luôn được đặt lên hàng đầu.</p>
                <div class="social-bnr-agileits about-agile">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>					
                    </ul>
                </div>
                <div class="team-img">
                    <img src="images/thuong.jpg" alt="">
                </div>
            </div>
            <div class="col-md-3 team-grids wow fadeInUp animated" data-wow-delay=".5s">
                <h5>Nhi <span>Nguyen</span></h5>
                <p>Chúng tôi chân thành cảm ơn sự hỗ trợ và hướng dẫn của Mr. Thuận và Mr. Ngô.</p>
                <div class="social-bnr-agileits about-agile">
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>					
                    </ul>
                </div>
                <div class="team-img">
                    <img src="images/t4.jpg" alt="">
                </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>	
<a href="#home" class="scroll" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
<script src="{{asset('js/jquery-2.1.4.min.js')}}"></script>
<script src="{{asset('js/numscroller-1.0.js')}}"></script>
<script src="{{asset('js/particles.js')}}"></script>
<script src="{{asset('js/app.js')}}"></script>
<script>
$(document).ready(function () {
    $(".dropdown").hover(
            function () {
                $('.dropdown-menu', this).stop(true, true).slideDown("fast");
                $(this).toggleClass('open');
            },
            function () {
                $('.dropdown-menu', this).stop(true, true).slideUp("fast");
                $(this).toggleClass('open');
            }
    );
});
</script>
<script src="{{asset('js/move-top.js')}}"></script>
<script src="{{asset('js/easing.js')}}"></script>
<script type="text/javascript">
jQuery(document).ready(function ($) {
    $(".scroll").click(function (event) {
        event.preventDefault();
        $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
    });
});
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $().UItoTop({easingType: 'easeOutQuart'});
    });
</script>
<script src="{{asset('js/bootstrap.js')}}"></script>
<script>
    $("span.menu").click(function () {
        $(".top-nav ul").slideToggle("slow", function () {
        });
    });
</script>
@endsection

resources/views/profile.blade.php
<html lang="en">
    <head>
        <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet" />
        <link rel="stylesheet" href="{{asset('css/ace.min.css')}}" />
        <link rel="stylesheet" href="{{asset('css/ace-skins.min.css')}}" />
        <link rel="stylesheet" href="{{asset('css/ace-rtl.min.css')}}" />
    </head>
    <body>
        <div class="container">
            <div class="page-content">
                <div class="page-header">
                    <h1>
                        User Profile Page
                        <div class="space-4"></div>
                        <small>                 
                            @if(Session::has('update_profile'))
                            <p class="bg-danger">{{session('update_profile') }}</p>
                            @endif
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="hr dotted"></div>

                        <div>
                            <form action="{{ route('profile.update', Auth::user()->id) }}" method="post" enctype='multipart/form-data'>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="_method" value="PUT">
                                <div id="user-profile-1" class="user-profile row">
                                    <div class="col-xs-12 col-sm-3 center">
                                        <div>
                                            <span class="profile-picture">
                                                <img src="{{ Auth::user()->avata_image }}" height="300" alt="" class="img-responsive img-rounded">
                                            </span>

                                            <div class="space-4"></div>

                                            <div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
                                                <div class="inline position-relative">
                                                    <a href="#" class="user-title-label dropdown-toggle" data-toggle="dropdown">
                                                        <i class="ace-icon fa fa-circle light-green"></i>
                                                        &nbsp;
                                                        <span class="white">{{ Auth::user()->username }} </span>
                                                    </a>                                 
                                                </div>

                                            </div>
                                            <div class="space-4"></div>
                                            <div class="profile-info-row {{ $errors->has('avata_image') ? 'has-error' : '' }}">                                 
                                                <input type="file" id="photo_id" name="avata_image" class="form-control" value=" ">
                                                <span class="text-danger">{{ $errors->first('avata_image') }}</span>
                                            </div>
                                        </div>
                                        <div class="space-6"></div>

                                        <div class="hr hr12 dotted"></div>

                                        <div class="hr hr16 dotted"></div>
                                    </div>

                                    <div class="col-xs-12 col-sm-9">
                                        <div class="space-12"></div>
                                        <div class="profile-user-info profile-user-info-striped">
                                            <div class="profile-info-row {{ $errors->has('username') ? 'has-error' : '' }}">
                                                <div class="profile-info-name"> Username </div>
                                                <input type="text" id="username" name="name" class="form-control" placeholder="Enter user name" value="{{ Auth::user()->username }} ">
                                                <span class="text-danger">{{ $errors->first('name') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('email') ? 'has-error' : '' }}">
                                                <div class="profile-info-name"> Email </div>
                                                <input type="text" id="email" name="email" class="form-control" value="{{ Auth::user()->email }} ">
                                                <span class="text-danger">{{ $errors->first('email') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('password') ? 'has-error' : '' }}" >
                                                <div class="profile-info-name">Old password </div>
                                                <input type="password" id="old_password" name="old_password" class="form-control" value="">
                                                <span class="text-danger">{{ $errors->first('password') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('password') ? 'has-error' : '' }}" >
                                                <div class="profile-info-name">New password </div>
                                                <input type="password" id="password" name="password" class="form-control" value="">
                                                <span class="text-danger">{{ $errors->first('password') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('password') ? 'has-error' : '' }}" >
                                                <div class="profile-info-name">Password-confirm</div>
                                                <input type="password" id="repassword" name="repassword" class="form-control" value="">
                                                <span class="text-danger">{{ $errors->first('password') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('address') ? 'has-error' : '' }}">
                                                <div class="profile-info-name"> Address </div>
                                                <input type="text" id="address" name="address" class="form-control" placeholder="" value="{{ Auth::user()->address }}">
                                                <span class="text-danger">{{ $errors->first('address') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('date') ? 'has-error' : '' }}">
                                                <div class="profile-info-name"> DOB </div>
                                                <input id="date" type="date" class="form-control" name="date" placeholder="" value="{{ Auth::user()->date_of_birth }}">
                                                <span class="text-danger">{{ $errors->first('date') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('gender') ? 'has-error' : '' }}">
                                                <div class="profile-info-name"> Gender </div>
                                                <select id="gender" class="form-control" name="gender">
                                                    <option hidden="" value="{{Auth::user()->gender}}">{{Auth::user()->gender}}</option>
                                                    <option value="Male">Male</option>
                                                    <option value="Female">Female</option>
                                                    <option value="Other">Other</option>
                                                </select>
                                                <span class="text-danger">{{ $errors->first('gender') }}</span>
                                            </div>

                                            <div class="profile-info-row {{ $errors->has('phone') ? 'has-error' : '' }}">
                                                <div class="profile-info-name"> Phone </div>
                                                <input id="phone" type="number" class="form-control" name="phone" placeholder="Your Phone" value="{{ Auth::user()->phone }}">
                                                <span class="text-danger">{{ $errors->first('phone') }}</span>
                                            </div>
                                        </div>

                                        <div class="space-20"></div>
                                        <div class="hr hr2 hr-double"></div>

                                        <div class="space-6"></div>

                                        <div class="left">
                                            <div class="row  col-md-7 form-group">
                                                <input type="submit" class="btn btn-success" value="Save" />
                                                <input type="hidden" value="{{ Session::token() }}" name="_token">
                                            </div>
                                            
                                            <div class="right">
                                                <a class="btn bnt-link" href="{{ url('/home') }}">
                                                    Back home
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/vieworders.blade.php
<html lang="en">
    <head>
        <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet" />
        <link rel="stylesheet" href="{{asset('css/ace.min.css')}}" class="ace-main-stylesheet" id="main-ace-style" />
        <link rel="stylesheet" href="{{asset('css/ace-skins.min.css')}}" />
        <link rel="stylesheet" href="{{asset('css/ace-rtl.min.css')}}" />
        <link rel="shortcut icon" href="images/img/food.png">
    </head>
    <body>
        <div class="space-24"></div>
        <div class="container">
            <div class="page-content">
                <div class="page-header">
                    <h1>
                        View Your Orders
                        <div class="space-12"></div>  
                        <small>                 
                            @if(Session::has('deleted_order'))
                            {{session('deleted_order')}}
                            @endif
                        </small>
                    </h1>
                </div><!-- /.page-header -->

                <div class="row">
                    <div class="col-xs-12">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="hr dotted"></div>

                        <div>

                            <div id="user-profile-1" class="user-profile row">
                                <div class="col-xs-12 col-sm-3 center">
                                    <form action="{{ route('profile.update', Auth::user()->id) }}" method="post" enctype='multipart/form-data'>
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="hidden" name="_method" value="PUT">
                                        <div>
                                            <span class="profile-picture">
                                                <img src="{{ Auth::user()->avata_image }}" height="300" alt="" class="img-responsive img-rounded">
                                            </span>

                                            <div class="space-4"></div>

                                            <div class="width-80 label label-info label-xlg arrowed-in arrowed-in-right">
                                                <div class="inline position-relative">
                                                    <a href="#" class="user-title-label dropdown-toggle" data-toggle="dropdown">
                                                        <i class="ace-icon fa fa-circle light-green"></i>
                                                        &nbsp;
                                                        <span class="white">{{ Auth::user()->username }} </span>
                                                    </a>
                                                    <div class="space-8"></div>

                                                    <div class="left">
                                                        <div class="row  col-md-7 form-group center">
                                                            <div class="foot-lnk">
                                                                <a class="btn btn-link" href="{{ url('/home') }}">
                                                                    Back home
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="space-4"></div>
                                        </div>
                                        <div class="space-6"></div>

                                        <div class="hr hr12 dotted"></div>
                                        <div class="hr hr16 dotted"></div>
                                    </form>
                                </div>
                                <div class="col-xs-12 col-sm-9">
                                    <div class="space-12"></div>
                                    <table class="table"> 
                                        <thead>
                                            <tr>
                                                <th>Id</th>
                                                <th>Order_date</th>
                                                <th>Customer</th>
                                                <th>Shipped_date</th>
                                                <th>Status</th>
                                                <th>Created_at</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @foreach($orders as $order)
                                            <tr>
                                                <td>{{$order->id}}</td>
                                                <td>{{$order->order_date}}</td>
                                                <td><a href="{{url('vieworders/'. $order->id.'/edit') }}">{{$order->full_name ? $order->full_name : 'Unname'}}</a></td>
                                                <td>{{$order->shipped_date}}</td>
                                                <td>Đang chờ giao</td>
                                                <td>{{$order->created_at}}</td>
                                                <td>
                                                    <form class="delete" id="delete" action="{{ route('vieworders.destroy', $order->id)}}" method="POST">
                                                        <input type="hidden" name="_method" value="DELETE">
                                                        <input type="hidden" name="_token" value="{{csrf_token()}}"/>
                                                        <input type="submit" class="btn btn-danger" value="Hủy hóa đơn">
                                                    </form>
                                                    <span><small>                 
                                                            @if(Session::has('undeleted_order'))
                                                            {{session('undeleted_order')}}
                                                            @endif
                                                        </small></span>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                    <div class="space-6"></div>

                                    <div class="row">
                                        <div class="col-lg-6 col-sm-offset-5">
                                            {{ $orders->render() }}
                                        </div>

                                    </div>
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>