routes/web.php

<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('', function () {
    $products = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(12)->get();
    $products_new = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(6)->get();
    return view('home', compact('products', 'products_new'));
    return view('home');
});





//Route::post('single/comment_product2', function () {
//    return array();
//});

Route::post('/login', 'LoginController@showLogin');
Route::post('/login', 'LoginController@processLogin');
Route::get('logout', function() {
    Auth::logout(); // logout user
    return Redirect::to('/login');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/products', 'HomeController@index1')->name('products');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/vieworders', 'HomeController@vieworders')->name('vieworders');
Route::resource('/vieworders', 'ViewOrderController');

Route::get('/products', 'HomeController@index1')->name('products');
Route::get('/single/{id}', 'HomeController@index2')->name('product_details');
Route::get('/category_products/{id}', 'HomeController@get_products_by_category')->name('product_category');
Route::get('/cart', 'HomeController@index3')->name('cart');
Route::get('/admin', 'HomeController@index4')->name('admin');
Route::get('admin/comments/{id}/reply', 'AdminCommentsController@getReplyComment');
Route::get('admin/categories/{id}/child_categories', 'AdminCategoriesController@getChildCategory');
Route::post('single/comment_product2', 'HomeController@comment_product')->name('comment_product2');
Route::post('single/reply_product', 'HomeController@reply_product')->name('reply_product');
Route::post('/edit/{id}','HomeController@del_img')->name('del_img');
Route::resource('/profile','ClientController');
Route::resource('admin/products', 'AdminProductController', array('as' => 'admin'));
Route::resource('admin/categories', 'AdminCategoriesController', array('as' => 'admin'));
Route::resource('admin/users', 'AdminUserController', array('as' => 'admin'));
Route::resource('admin/comments', 'AdminCommentsController', array('as' => 'admin'));
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('comment', function(Request $request) {
    $comment = App\Comment::create($request->input());
    return response()->json($comment);
});

Route::get('/getsize', 'HomeController@getSizeProduct');
Route::get('/addtocart', 'HomeController@getSizeAddtoCart');
Route::get('/addtocart/{id}', 'HomeController@getAddToCart');
Route::get('product/delete/{id}', 'HomeController@removeItem');
Route::get('product/deductbyone/{id}', 'HomeController@deductByOne');
Route::get('/shoppingcart', 'HomeController@getCart');
Route::get('/shipping', 'HomeController@Shipping');
Route::get('search','HomeController@getSearch')->name('search'); //search by name product

Route::get('/search-price','HomeController@searchprice')->name('searchprice'); //search by price, size...
//Route::post('/searchprice', 'HomeController@searchprice');

Route::group(['middleware' => ['adminLogin']], function () {
    Route::resource('admin/users','AdminUserController', array('as' =>'admin'));
    Route::resource('admin/categories','AdminCategoriesController', array('as' =>'admin'));
    Route::resource('admin/products','AdminProductController', array('as' =>'admin'));
    Route::resource('admin/comments','AdminCommentsController', array('as' =>'admin'));    
});
Route::resource('admin/orders','OrderController', array('as' => 'admin'));

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    
    protected $fillable = [
        'username','date_of_birth','gender','address','email','phone','full_name','avata_image',
        'password','is_active','is_delete'
    ];
    
    protected $hidden = [
        'password','remember_token',
    ];
    public function category() {
        return $this->belongsTo('App\User');
    }
    
    public function images() {
        return $this->hasMany('App\Image');
    }
    public function photo(){
        return $this->images()->get()->first();
    }
}

resources/views/admin/users/createUser.blade.php
@extends('layouts.admin')
@section('content')
<h1>Create User</h1>

    @if(count($errors))
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.
            <br/>
            <ul>
                @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    
    <div class="container">
        <form action="{{ url('/admin/users') }}" method="post" enctype='multipart/form-data'>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            
            <div class=" row col-md-7 form-group {{ $errors->has('username') ? 'has-error' : '' }}">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" class="form-control" placeholder="Enter user name" value="{{ old('username') }}" required>
                <span class="text-danger">{{ $errors->first('username') }}</span>
            </div> 
            
            <div class="row col-md-7 form-group{{ $errors->has('address') ? ' has-error' : '' }}">
                <label for="address">Address:</label>
                <input id="address" type="text" class="form-control" name="address" value="{{ old('address') }}" placeholder="Your Address" required>
                <span class="text-danger">{{ $errors->first('address') }}</span>
            </div>

            <div class=" row col-md-7  form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" value="{{ old('email') }}">
                <span class="text-danger">{{ $errors->first('email') }}</span>
            </div>
            
            <div class=" row  col-md-7 form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
                <label for="is_active">Activate Account:</label>
                <input type="checkbox" id="is_active" name="is_active" value="{{ old('is_active') }}">
                <span class="text-danger">{{ $errors->first('is_active') }}</span>
            </div> 

            <div class="row  col-md-7 form-group {{ $errors->has('gender') ? ' has-error' : '' }}">
                <label for="gender">Gender:</label>
                
                <select id="gender" class="form-control" name="gender" required>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                    <option value="Other">Other</option>
                </select> 
                <span class="text-danger">{{ $errors->first('gender') }}</span>
            </div>

            <div class="row col-md-7 form-group {{ $errors->has('date') ? ' has-error' : '' }}">
                <label for="date">Birthday:</label>
                <input id="date" type="date" class="form-control" name="date" placeholder="Input your birthday" value="{{ old('date') }}" required>
                <span class="text-danger">{{ $errors->first('date') }}</span>
            </div>

            <div class="row col-md-7 form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
                <label for="phone">Phone:</label>
                <input id="phone" type="number" class="form-control" name="phone" placeholder="Your Phone" value="{{ old('phone') }}" required>
                <span class="text-danger">{{ $errors->first('phone') }}</span>
            </div>
            
            <div class=" row col-md-7 form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" value="{{ old('password') }}">
                <span class="text-danger">{{ $errors->first('password') }}</span>
            </div> 
            
            <div class="row col-md-7 form-group {{ $errors->has('avatar_image') ? 'has-error' : '' }}">
                <label for="avatar_image">Avatar:</label>
                <input type="file" id="avata_image" name="avatar_image" class="form-control" value="{{ old('avatar_image') }}">
                <span class="text-danger">{{ $errors->first('avatar_image') }}</span>
            </div> 

            <div class="row col-md-7 form-group">
                <input type="submit" class="btn btn-success" value="Create User" />
            </div>
        </form>
    </div>
        
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')
<h1>Edit User</h1>

<div class="container">
    <form action="{{ route('admin.users.update', $users->id) }}" method="post" enctype='multipart/form-data'>
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="PUT">

        <div class=" row col-md-7 form-group {{ $errors->has('name') ? 'has-error' : '' }}">
            <label for="name">Username:</label>
            <input type="text" id="username" name="name" class="form-control" placeholder="Enter user name" value="{{ $users ->username }}">
            <span class="text-danger">{{ $errors->first('name') }}</span>
        </div> 

        <div class="row col-md-7 form-group {{ $errors->has('address') ? ' has-error' : '' }}">
            <label for="address">Address:</label>
            <input type="text" id="address" name="address" class="form-control" placeholder="Your Address" value="{{ $users ->address }}">
            <span class="text-danger">{{ $errors->first('address') }}</span>
        </div>

        <div class=" row col-md-7  form-group {{ $errors->has('email') ? 'has-error' : '' }}">
            <label for="email">Email:</label>
            <input type="text" id="email" name="email" class="form-control" placeholder="Enter Email" value="{{ $users ->email }}">
            <span class="text-danger">{{ $errors->first('email') }}</span>
        </div>

        <!--
                    <div class=" row col-md-12 form-group {{ $errors->has('firstname') ? 'has-error' : '' }}">
                        <label for="categoryname">Category:</label>
                        <input type="text" id="username" name="categoryname" class="form-control" placeholder="Active" value="{{ old('categoryname') }}">
                        <span class="text-danger">{{ $errors->first('categoryname') }}</span>
                    </div> -->

        <div class=" row  col-md-7 form-group {{ $errors->has('is_active') ? 'has-error' : '' }}">
            <label for="is_active">Activate Account:</label>
            <input type="checkbox" id="is_active" name="is_active" value="1" @if($users ->is_active ==1) checked @endif>
                   <span class="text-danger">{{ $errors->first('is_active') }}</span>
        </div> 

        <div class="row  col-md-7 form-group {{ $errors->has('gender') ? ' has-error' : '' }}">
            <label for="gender">Gender:</label>

            <select id="gender" class="form-control" name="gender">
                <option hidden="" value="{{$gender->gender}}">{{$gender->gender}}</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
            </select>
            <span class="text-danger">{{ $errors->first('gender') }}</span>
        </div>

        <div class="row col-md-7 form-group {{ $errors->has('date') ? ' has-error' : '' }}">
            <label for="date">Birthday:</label>
            <input id="date" type="date" class="form-control" name="date" placeholder="Input your birthday" value="{{ $users ->date_of_birth }}">
            <span class="text-danger">{{ $errors->first('date') }}</span>
        </div>

        <div class="row col-md-7 form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
            <label for="phone">Phone:</label>
            <input id="phone" type="number" class="form-control" name="phone" placeholder="Your Phone" value="{{ $users ->phone }}">
            <span class="text-danger">{{ $errors->first('phone') }}</span>
        </div>

        <div class="row col-md-7 form-group">
            <img src="{{$users->avata_image ? asset( $users->avata_image ): 'http://placehold.it/400x400'}}" height="300" alt="" class="img-responsive img-rounded">
        </div>

        <div class="row col-md-7 form-group {{ $errors->has('avata_image') ? 'has-error' : '' }}">
            <label for="avata_image">Thumnail:</label>
            <input type="file" id="photo_id" name="avata_image" class="form-control" value="value="{{ $users->avata_image }}"">
            <span class="text-danger">{{ $errors->first('avata_image') }}</span>
        </div> 

        <div class=" row  col-md-7 form-group {{ $errors->has('password') ? 'has-error' : '' }}">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" class="form-control" value="">
            <span class="text-danger">{{ $errors->first('password') }}</span>
        </div> 


        <div class="row  col-md-7 form-group">
            <input type="submit" class="btn btn-success" value="Edit User" />
        </div>

    </form>

    <form action="{{ route('admin.users.destroy', $users->id)}}" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{csrf_token()}}"/>
        <div class="row  col-md-7 form-group">
            <input type="submit" class="btn btn-danger" value="Delete User"/>
        </div>
    </form>
</div>

@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

@if(Session::has('create_user'))
<p class="bg-danger">{{session('create_user')}}</p>
@endif

@if(Session::has('deleted_use'))
<p class="bg-danger">{{session('deleted_user') }}</p>
@endif

@if(Session::has('update_user'))
<p class="bg-danger">{{session('update_user') }}</p>
@endif

<h1>Users</h1>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Email</th>
            <th>Active</th>
            <th>Phone</th>
            <th>Gender</th>
            <th>Birthday</th>
            <th>Address</th>
            <th>Role</th>
            <th>Created</th>
            <th>Updated</th>
        </tr>
    </thead>

    <tbody>
        @if($users)

        @foreach ($users as $user) 
        <tr>
            <td>{{$user->id}}</td>
            <td><img height="50" width="50" src="{{$user['avata_image'] ? asset($user->avata_image) : 'http://placehold.it/400x400' }}" alt="image"></td>
            <td><a href="{{route('admin.users.edit',$user->id) }}" > {{$user->username}}</a></td>
            <td>{{$user->email}}</td>
            <td>{{$user->is_active?'active':'inactive'}}</td>
            <td>{{$user->phone}}</td>
            <td>{{$user->gender}}</td>
            <td>{{$user->date_of_birth}}</td>
            <td>{{$user->address}}</td>
            <td>{{$user->role}}</td>
            <td>{{$user->created_at}}</td>
            <td>{{$user->updated_at}}</td>
        </tr>
        @endforeach
        @endif

    </tbody>
</table>

<!--phần phân trang trong lavavel-->
<div class="row">
    <div class="col-lg-6 col-sm-offset-5">
        {{$users->render()}}
    </div>
</div>
@stop