routes/web.php

<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('', function () {
    $products = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(12)->get();
    $products_new = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(6)->get();
    return view('home', compact('products', 'products_new'));
    return view('home');
});





//Route::post('single/comment_product2', function () {
//    return array();
//});

Route::post('/login', 'LoginController@showLogin');
Route::post('/login', 'LoginController@processLogin');
Route::get('logout', function() {
    Auth::logout(); // logout user
    return Redirect::to('/login');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/products', 'HomeController@index1')->name('products');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/vieworders', 'HomeController@vieworders')->name('vieworders');
Route::resource('/vieworders', 'ViewOrderController');

Route::get('/products', 'HomeController@index1')->name('products');
Route::get('/single/{id}', 'HomeController@index2')->name('product_details');
Route::get('/category_products/{id}', 'HomeController@get_products_by_category')->name('product_category');
Route::get('/cart', 'HomeController@index3')->name('cart');
Route::get('/admin', 'HomeController@index4')->name('admin');
Route::get('admin/comments/{id}/reply', 'AdminCommentsController@getReplyComment');
Route::get('admin/categories/{id}/child_categories', 'AdminCategoriesController@getChildCategory');
Route::post('single/comment_product2', 'HomeController@comment_product')->name('comment_product2');
Route::post('single/reply_product', 'HomeController@reply_product')->name('reply_product');
Route::post('/edit/{id}','HomeController@del_img')->name('del_img');
Route::resource('/profile','ClientController');
Route::resource('admin/products', 'AdminProductController', array('as' => 'admin'));
Route::resource('admin/categories', 'AdminCategoriesController', array('as' => 'admin'));
Route::resource('admin/users', 'AdminUserController', array('as' => 'admin'));
Route::resource('admin/comments', 'AdminCommentsController', array('as' => 'admin'));
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('comment', function(Request $request) {
    $comment = App\Comment::create($request->input());
    return response()->json($comment);
});

Route::get('/getsize', 'HomeController@getSizeProduct');
Route::get('/addtocart', 'HomeController@getSizeAddtoCart');
Route::get('/addtocart/{id}', 'HomeController@getAddToCart');
Route::get('product/delete/{id}', 'HomeController@removeItem');
Route::get('product/deductbyone/{id}', 'HomeController@deductByOne');
Route::get('/shoppingcart', 'HomeController@getCart');
Route::get('/shipping', 'HomeController@Shipping');
Route::get('search','HomeController@getSearch')->name('search'); //search by name product

Route::get('/search-price','HomeController@searchprice')->name('searchprice'); //search by price, size...
//Route::post('/searchprice', 'HomeController@searchprice');

Route::group(['middleware' => ['adminLogin']], function () {
    Route::resource('admin/users','AdminUserController', array('as' =>'admin'));
    Route::resource('admin/categories','AdminCategoriesController', array('as' =>'admin'));
    Route::resource('admin/products','AdminProductController', array('as' =>'admin'));
    Route::resource('admin/comments','AdminCommentsController', array('as' =>'admin'));    
});
Route::resource('admin/orders','OrderController', array('as' => 'admin'));

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Product extends Model {

    use FullTextSearch;

use Notifiable;

    protected $searchable = [
        'name',
    ];
    protected $fillable = [
        'name',
        'category_id',
        'description',
    ];

    public function category() {
        return $this->belongsTo('App\Category');
    }
    public function images() {
        return $this->hasMany('App\Image','product_id','id');
    }
    public function thumbnail() {
        return $this->images()->where([['is_thumbnail', 1], ['is_delete', 0]])->get()->last();
    }
    
    public function image() {
        return $this->images()->where([['is_thumbnail',0],['is_delete',0]])->get();
    }

//    public function photo(){
//        return $this->images()->get()->first();
//    }

    public function price() {
        return $this->hasMany('App\PriceSizes','product_id','id');
    }

    public function is_price() {
        return $this->price()->where([['is_price', 0], ['is_delete', 0]])->get()->last();
    }

//    public function size(){
//        return $this->price()->get()->first();
//    }

    public function order_details() {
        return $this->hasMany('App\OrderDetail','product_id','id');
    }

}

resources/views/admin/products/create.blade.php
@extends('layouts.admin')

@section('content')
@include('includes.tinyeditor')

<h1>Create Products</h1>

<div class="container">

    <form action="{{ route('admin.products.store') }}" method="post" enctype='multipart/form-data'>
        <input type="hidden" name="_token" value="{{ csrf_token() }}"/>



        <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="Enter product name" value="{{ old('name') }}" required>
            <span class="text-danger">{{ $errors->first('name') }}</span>
        </div>    

        <div class=" form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
            <label for="category_id">Category:</label>
            <select class="form-control" id="category_id" name="category_id" >
                @foreach ($child_categories as $key => $name  )
                <option value="{{$name->id}}">{{$name->name}}</option>
                @endforeach   
            </select>                
            <span class="text-danger">{{ $errors->first('category_id') }}</span>
        </div>  


        <div class="  form-group {{ $errors->has('link_image') ? 'has-error' : '' }}">
            <label for="link_image">Ảnh chính:</label>
            <input type="file" id="link_image" name="link_image" class="form-control" value="{{ old('link_image') }}">
            <span class="text-danger">{{ $errors->first('link_image') }}</span>
        </div> 
        <div class="  form-group {{ $errors->has('image') ? 'has-error' : '' }}">
            <label for="image">Ảnh phụ:</label>
            <input type="file" id="image" name="image" class="form-control" value="{{ old('image') }}">
            <span class="text-danger">{{ $errors->first('image') }}</span>
        </div> 

        <div class=" form-group {{ $errors->has('description') ? 'has-error' : '' }}">
            <label for="body">Descriptions:</label>
            <textarea class="form-control" rows="5" id="body" name="description">{{ old('description') }}</textarea>
            <span class="text-danger">{{ $errors->first('description') }}</span>
        </div> 

        <div class=" form-group {{ $errors->has('size') ? 'has-error' : '' }}">
            <label for="size">Size:</label>
            <select id="size" class="form-control" name="size" required>
                <option value="l">Lớn</option>
                <option value="m">Trung</option>
                <option value="s">Nhỏ</option>
            </select>
            <span class="text-danger">{{ $errors->first('size') }}</span>
        </div> 

        <div class=" form-group {{ $errors->has('quality') ? 'has-error' : '' }}">
            <label for="quality">Quality:</label>
            <input type="text" id="title" name="quality" class="form-control" placeholder="" value="{{ old('quality') }}">
            <span class="text-danger">{{ $errors->first('quality') }}</span>
        </div>  

        <div class=" form-group {{ $errors->has('price') ? 'has-error' : '' }}">
            <label for="price">Price:</label>
            <input type="number" id="title" name="price" class="form-control" placeholder="" value="{{ old('price') }}">
            <span class="text-danger">{{ $errors->first('price') }}</span>
        </div>

        <div class=" form-group {{ $errors->has('quantity') ? 'has-error' : '' }}">
            <label for="quantity">Quantity:</label>
            <input type="number" id="title" name="quantity" class="form-control" placeholder="" value="{{ old('quantity') }}">
            <span class="text-danger">{{ $errors->first('quantity') }}</span>
        </div>


        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Create Product" />
        </div>        
</div>
<div class="col-md-1"></div>

</form>  
@stop

resources/views/admin/products/edit.blade.php
@extends('layouts.admin')
@section('content')
@include('includes.tinyeditor')

<h1>Create Products</h1>

<div class="container">
    <form action="{{ route('admin.products.update', $product->id) }}" method="post" enctype='multipart/form-data'>
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="PUT">

        <div class=" form-group {{ $errors->has('name') ? 'has-error' : '' }}">
            <label for="name">Name:</label>
            <input type="text" id="title" name="name" class="form-control" placeholder="Enter title" value="{{ $product->name }}">
            <span class="text-danger">{{ $errors->first('name') }}</span>
        </div>        
        <div class=" form-group {{ $errors->has('category_id') ? 'has-error' : '' }}">
            <label for="category_id">Category:</label>
            <select class="form-control" id="category_id" name="category_id" >
                @foreach ($child_categories as $id => $name)
                <option value="{{$id}}" {{ $id == $product->category->id ? 'selected="selected"' : '' }}>{{$name}}</option>
                @endforeach   
            </select>                
            <span class="text-danger">{{ $errors->first('category_id') }}</span>
        </div>  

        <div class="form-group " style="width:  200px">
            <img src="{{$product->thumbnail() ? asset( $product->thumbnail()->link_image ): 'http://placehold.it/400x400'}}" height="300" alt="" class="img-responsive img-rounded">
        </div>

        <br>

        <div class="  form-group {{ $errors->has('link_image') ? 'has-error' : '' }}">
            <label for="link_image">Thumbnail:</label>
            <input type="file" id="link_image" name="link_image" class="form-control" value="{{ $product->thumbnail()->link_image }}">
            <span class="text-danger">{{ $errors->first('link_image') }}</span>
        </div> 

        <div class="space-4"></div>
        <div class="space-4"></div>

        <div class="row" id="show_image_delete">
            @foreach ($product->image() AS $img)
            <div class="col-md-3">
                <div class="form-group" style="width: 200px">
                    <input type="hidden" id="image_id" value="{{$img->id}}">
                    <input type="hidden" id="product_id" value="{{$product->id}}">
                    <img style="width: 300px; height: 250px" src="{{$img->link_image ? asset ($img->link_image ): 'http://placehold.it/400x400'}}" height="300" class="img-responsive img-rounded">
                    <div class="space-4"></div>    
                    <button type="button" class="" id="image_delete{{$img->id}}" onclick="deleteImages({{$img->id}})" value="{{$img->id}}">Delete</button>    
                </div>                   
            </div>             
            @endforeach
        </div>      

        <div class="  form-group {{ $errors->has('image') ? 'has-error' : '' }}">
            <label for="image">Image:</label>
            <input type="file" id="link_image" name="image" class="form-control" value="{{ old('image') }}">
            <span class="text-danger">{{ $errors->first('image') }}</span>
        </div>

        <div class="space-4"></div>

        <div class=" form-group {{ $errors->has('description') ? 'has-error' : '' }}">
            <label for="body">Descriptions:</label>
            <textarea class="form-control" rows="5" id="body" name="description">{{ $product->description }}</textarea>
            <span class="text-danger">{{ $errors->first('description') }}</span>
        </div> 

        <div class=" form-group {{ $errors->has('size') ? 'has-error' : '' }}">
            <label for="size">Size:</label>
            <select id="size" class="form-control" name="size" required>
                <option hidden="" value="{{$price_sizes->size}}">{{$price_sizes->size}}</option>
                <option value="l">l</option>
                <option value="m">m</option>
                <option value="s">s</option>
            </select>
            <span class="text-danger">{{ $errors->first('size') }}</span>
        </div>

        <div class=" form-group {{ $errors->has('quality') ? 'has-error' : '' }}">
            <label for="quality">Quality:</label>
            <input type="text" id="quality" name="quality" class="form-control" placeholder="" value="{{ $product->is_price()->quality }}">
            <span class="text-danger">{{ $errors->first('quality') }}</span>
        </div>

        <div class=" form-group {{ $errors->has('price') ? 'has-error' : '' }}">
            <label for="price">Price:</label>
            <input type="number" id="price" name="price" class="form-control" placeholder="" value="{{ $product->is_price()->price }}"/>
            <span class="text-danger">{{ $errors->first('price') }}</span>
        </div>

        <div class=" form-group {{ $errors->has('quantity') ? 'has-error' : '' }}">
            <label for="quantity">Quantity:</label>
            <input type="number" id="quantity" name="quantity" class="form-control" placeholder="" value="{{ $product->is_price()->quantity }}">
            <span class="text-danger">{{ $errors->first('quantity') }}</span>
        </div>

        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
    </form>
</div>



<div class="row">
    @include('includes.form_error')
</div>
@stop

resources/views/admin/products/index.blade.php
@extends('layouts.admin')
@section('content')

<div class="container">
    <h1 style="color: #0099CC; text-align: center; margin:20px;">Products Management</h1>
    @if (session('create_product'))
    <div class="alert alert-success">
        {{ session('create_product') }}
    </div>
    @endif
    @if (session('update_product'))
    <div class="alert alert-success">
        {{ session('update_product') }}
    </div>
    @endif
    <table class="table"> 
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Photo</th>
                <th>Category</th>
                <th>Description</th>
                <th>Size</th>
                <th>Quality</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Created at</th>
                <th>Updated at</th>
            </tr>
        </thead>

        <tbody>
            @foreach($products as $product)
            <tr>
                <td>{{$product->id}}</td>
                <td><a href="{{ url('admin/products/'. $product->id.'/edit') }}">{{$product->name}}</a></td>        
                <td><img width="75" height="60" src="{{$product->thumbnail()? asset( $product->thumbnail()->link_image ): 'http://placehold.it/400x400'}}" alt=""></td>
                <td>{{$product->category ? $product->category->name : 'Uncategorized'}}</td>
                <td>{{str_limit($product->description)}}</td>
                <td>{{$product->is_price() ? $product->is_price() ->size :  'Unsized'}}</td>
                <td>{{$product->is_price() ? $product->is_price() ->quality :  'Unqualitied'}}</td>
                <td>{{$product->is_price() ? $product->is_price() ->price :  'Unpriced'}}</td>
                <td>{{$product->is_price() ? $product->is_price() ->quantity :  'Unquantity'}}</td>
                <td>{{$product->created_at->diffForhumans()}}</td>
                <td>{{$product->updated_at->diffForhumans()}}</td>

            </tr>
            @endforeach



        </tbody>
    </table>


    <div class="row">
        <div class="col-lg-6 col-sm-offset-5">
            {{ $products->render() }}
        </div>

    </div>



    @stop