routes/web.php

<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('', function () {
    $products = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(12)->get();
    $products_new = App\Product::where('is_delete', '=', '0')->orderBy('created_at', 'desc')->limit(6)->get();
    return view('home', compact('products', 'products_new'));
    return view('home');
});





//Route::post('single/comment_product2', function () {
//    return array();
//});

Route::post('/login', 'LoginController@showLogin');
Route::post('/login', 'LoginController@processLogin');
Route::get('logout', function() {
    Auth::logout(); // logout user
    return Redirect::to('/login');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function () {
    Route::get('/products', 'HomeController@index1')->name('products');
});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/profile', 'HomeController@profile')->name('profile');

Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/vieworders', 'HomeController@vieworders')->name('vieworders');
Route::resource('/vieworders', 'ViewOrderController');

Route::get('/products', 'HomeController@index1')->name('products');
Route::get('/single/{id}', 'HomeController@index2')->name('product_details');
Route::get('/category_products/{id}', 'HomeController@get_products_by_category')->name('product_category');
Route::get('/cart', 'HomeController@index3')->name('cart');
Route::get('/admin', 'HomeController@index4')->name('admin');
Route::get('admin/comments/{id}/reply', 'AdminCommentsController@getReplyComment');
Route::get('admin/categories/{id}/child_categories', 'AdminCategoriesController@getChildCategory');
Route::post('single/comment_product2', 'HomeController@comment_product')->name('comment_product2');
Route::post('single/reply_product', 'HomeController@reply_product')->name('reply_product');
Route::post('/edit/{id}','HomeController@del_img')->name('del_img');
Route::resource('/profile','ClientController');
Route::resource('admin/products', 'AdminProductController', array('as' => 'admin'));
Route::resource('admin/categories', 'AdminCategoriesController', array('as' => 'admin'));
Route::resource('admin/users', 'AdminUserController', array('as' => 'admin'));
Route::resource('admin/comments', 'AdminCommentsController', array('as' => 'admin'));
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('comment', function(Request $request) {
    $comment = App\Comment::create($request->input());
    return response()->json($comment);
});

Route::get('/getsize', 'HomeController@getSizeProduct');
Route::get('/addtocart', 'HomeController@getSizeAddtoCart');
Route::get('/addtocart/{id}', 'HomeController@getAddToCart');
Route::get('product/delete/{id}', 'HomeController@removeItem');
Route::get('product/deductbyone/{id}', 'HomeController@deductByOne');
Route::get('/shoppingcart', 'HomeController@getCart');
Route::get('/shipping', 'HomeController@Shipping');
Route::get('search','HomeController@getSearch')->name('search'); //search by name product

Route::get('/search-price','HomeController@searchprice')->name('searchprice'); //search by price, size...
//Route::post('/searchprice', 'HomeController@searchprice');

Route::group(['middleware' => ['adminLogin']], function () {
    Route::resource('admin/users','AdminUserController', array('as' =>'admin'));
    Route::resource('admin/categories','AdminCategoriesController', array('as' =>'admin'));
    Route::resource('admin/products','AdminProductController', array('as' =>'admin'));
    Route::resource('admin/comments','AdminCommentsController', array('as' =>'admin'));    
});
Route::resource('admin/orders','OrderController', array('as' => 'admin'));

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Category extends Model {

    use Notifiable;

    protected $fillable = [
        'parent_id', 'name', 'description', 'is_delete'
    ];

    public function parent() {
        return $this->belongsTo('App\Category', 'parent_id', 'id');
    }

    public function category_parent() {
        return $this->parent()->where([['parent_id', 0], ['is_delete', 0]])->get();
    }
    
    public function category_pa(){
        return $this->where([['parent_id', 0], ['is_delete', 0]])->get();
    }
    
    public function children() {
        return $this->hasMany('App\Category', 'parent_id', 'id');
    }

}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
<h1 style="color: #0099CC; text-align: center; margin-top: 10px;">Categories</h1>
@if(Session::has('deleted_category'))
<p class="bg-danger">{{session('deleted_category')}}</p>
@endif
<div class="container">
    <form action="{{route('admin.categories.update', $category->id)}}" method="POST">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="_method" value="PUT">

        <div class="row col-md-4 form-group {{ $errors->has('name') ? 'has-error' : '' }} ">           
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="Enter name" value="{{ $category->name}}">
            <span class="text-danger">{{ $errors->first('name') }}</span>

            <label for="parent">Chứa trong:</label>
            <select class="form-control" id="category_id" name="parent_id" >               
                @foreach ($category->category_parent() AS $cate)
                <option value="{{$cate->id}}">{{$cate->name}}</option> 
                @endforeach
                @foreach ($category->category_pa() AS $cate_pa)
                <option value="{{$cate_pa->id}}">{{$cate_pa->name}}</option> 
                @endforeach
            </select>    

            <label for="description" style="margin-top: 20px;">Description:</label>
            <input type="text" id="description" name="description" class="form-control" placeholder="Enter description" value="{{$category->description}}">
            <span class="text-danger">{{ $errors->first('description') }}</span> 

            <div class="form-group" style="margin-top: 10px;">
                <input type="submit" class="btn btn-success" value="Edit Category" />
            </div>
        </div>
        <div class="row col-md-8 form-group" style="margin-left: 10px;">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Parent ID</th>
                        <th>Description</th>
                        <th>Created date</th> 
                        <th>Updated date</th>   
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>{{$category->id}}</th>
                        <th>{{$category->name}}</th>
                        <th>
                            @foreach ($category->category_parent() AS $cate)
                            {{$cate->name}}
                            @endforeach
                        </th>
                        <th>{{$category->description}}</th>
                        <th>{{$category->created_at}}</th>
                        <th>{{$category->updated_at->diffForhumans()}}</th>
                    </tr>

                </tbody>
            </table>
        </div>
    </form>
    <div class="col-md-8" style="margin-top: 80px; margin-left: 10px;">
        <form action="{{ route('admin.categories.destroy',$category->id) }}" method="POST" >
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <div class="form-group">
                <input type="submit" class="btn btn-danger" value="Delete Category" />
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')
<h1 style="color: #0099CC; text-align: center; margin-top: 10px;">Categories</h1>
@if(Session::has('deleted_category'))
<p class="bg-danger">{{session('deleted_category')}}</p>
@endif
<div class="container">
    <!--    <form action="" method="post">-->
    <form action="{{route('admin.categories.store')}}" method="post">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <div class="row col-md-4 form-group {{ $errors->has('name') ? 'has-error' : '' }} ">           
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" class="form-control" placeholder="Enter name" value="{{ old('name') }}">
            <span class="text-danger">{{ $errors->first('name') }}</span><br>
            <label for="parent">Chứa trong:</label>
            <select class="form-control" id="category_id" name="parent_id" >
                <option value="0" selected="true">--Parent Category--</option>
                @foreach ($categories as $category  )
                <option value="{{$category->id}}">{{$category->name}}</option>
                @endforeach   
            </select>                
            <span class="text-danger">{{ $errors->first('category_id') }}</span>
            <label for="description" style="margin-top: 20px;">Description:</label>
            <input type="text" id="description" name="description" class="form-control" placeholder="Enter description" value="{{ old('description') }}">
            <span class="text-danger">{{ $errors->first('description') }}</span> 

            <div class="form-group" style="margin-top: 10px;">
                <input type="submit" class="btn btn-success" value="Create Category" />
            </div>
        </div>

        <div class="row col-md-8 form-group" style="margin-left: 10px;">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Parent Category</th>
                        <th>Description</th>
                        <th>Created date</th> 
                        <th>Updated date</th>
                        <th>Action</th>
                </thead>
                <tbody>
                    @if($cate)
                    @foreach($cate as $category)
                    <tr>
                        <th>{{$category->id}}</th>
                        <th>{{$category->name}}</th>
                        <th>
                            @if (($category->parent_id) == 0)
                            Thư mục cha
                            @else
                            {{$category->parent ? $category->parent ->name : 'Uncategorized'}}         
                            @endif
                        </th>
                        <th>{{$category->description}}</th>
                        <th>{{$category->created_at->diffForhumans()}}</th>
                        <th>{{$category->updated_at->diffForhumans()}}</th>
                        <th><a href="{{ url('admin/categories/'.$category->id.'/edit') }}">Edit</a></th>
                    </tr>
                    @endforeach
                    @endif
                </tbody>
            </table>
            <div class="row">
                <div class="col-lg-6 col-sm-offset-5">
                    {{ $cate->render() }}
                </div>
            </div>
        </div>
    </form>
</div>
@endsection